name: Upload Python Package

on:
  push:
    branches:
      - main  # 或者你希望触发的分支名，例如 'master'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
         python3 -m pip install --upgrade pip build setuptools wheel twine
    - name: List files in the repository
      run: ls -la
    - name: Install the package locally
      run: ls -al easy_pyweb
    - name: Current directory
      run: pwd
    - name: Build and Publish package
      env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}  # 确保在仓库设置中添加了这个 secret
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}  # 确保在仓库设置中添加了这个 secret
      run: |
          python3 -m build
          python3 -m twine upload dist/*
